"""empty message

Revision ID: 3cd9c87df92e
Revises: 82ea0a1082ae
Create Date: 2022-06-01 12:46:15.296028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd9c87df92e'
down_revision = '82ea0a1082ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('is_upcoming', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'is_upcoming')
    # ### end Alembic commands ###
