"""empty message

Revision ID: e76e9dd7e400
Revises: eac81f2a8b1b
Create Date: 2022-06-03 04:14:28.131068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76e9dd7e400'
down_revision = 'eac81f2a8b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('create_dt', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('create_dt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'create_dt')
    op.drop_column('Artist', 'create_dt')
    # ### end Alembic commands ###
