"""empty message

Revision ID: eac81f2a8b1b
Revises: d8fac4500909
Create Date: 2022-06-02 16:16:22.672082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac81f2a8b1b'
down_revision = 'd8fac4500909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city', sa.String(), nullable=True))
    op.add_column('Artist', sa.Column('state', sa.String(), nullable=True))
    op.drop_constraint('Artist_city_id_fkey', 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'city_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Artist_city_id_fkey', 'Artist', 'City', ['city_id'], ['id'])
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'city')
    # ### end Alembic commands ###
